version: "3.8"
services:
  postgresdb:
    image: postgres:13
    environment:
      - POSTGRES_USER=supermaker
      - POSTGRES_PASSWORD=superpasswd
      - POSTGRES_DB=taxi
    ports:
      - "2345:5432" # I already have a postgres running on 5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
  lab:
    image: quay.io/jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: ./
        target: /home/jovyan/work
    command: >
      sh -c "pip install psycopg2-binary && jupyter lab"
    depends_on:
      - postgresdb

volumes:
  postgres_data:
